# Site settings
title: Alva Fandrey
email: af222ug@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
    En samlingssida för mina projekt. Student vid Linnéuniversitetet, Kalmar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: alvaaf_
github_username:  afandrey

# Build settings
markdown: kramdown
